### PR TITLE
Moving getSession() into client from useSupabaseUser()

### LINKED ISSUE #236: Global auth middleware always redirects to /login on SSR:false routes
### Version
@nuxtjs/supabase: 
nuxt: 

### Steps to reproduce

On a page that is not server-side rendered the auth middleware is always redirecting to the login page, regardless if there is a valid session or not. This is due to the fact that useSupabaseUser is not returning a user, even if a valid session exists. This can be reproduces by adding a page to the route rules with SSR:false, or setting SSR:false for the entire app. For the latter, the auth middleware works once, but fails on page refresh.

### What is Expected?

The middleware should only redirect to login when there is no valid session / user, and refreshing the session fails.

### PR DESCRIPTION
**Pull request by Aietes**
Resolves #236 

Properly updating useSupabaseUser()

## Types of changes

- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

Using a different approach to check the session validity. The getSession() method has been moved into the supabase.client.ts, it now ensures an existing session in local storage will be reused and refreshed when a client is created. It also ensures useSupabaseUser() is updated according to the auth events occurring in the supabase-js client. This should solve the issues with non-SSR pages.

The downside of this approach is that an actual check for a session is only occurring in the setup function of the supabase.client, which occurs only once, or on refresh or switching to a different SSR mode route. The rest of the module relies on useSupabaseUser to accurately reflect a valid session, and useSupabaseUser() relies on useState(), which is updated on auth events from the supabase client.

This is probably fine in most cases, but a condition can occur in which useSupabaseUser() returns a user from useState(), when there is no valid session and user in place, as an explicit check doesn't occur. This can lead to a situation in which queries to RLS-protected tables return no data, and it's not apparent that the auth state is responsible. However, calling useSupabaseClient().auth.getSession() anywhere in the app should fix that state.

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes (if not applicable, please state why)

### CODE REVIEW

File: src/runtime/composables/useSupabaseUser.ts [hunk 1]
```diff
@@ -1,22 +1,6 @@
...
-import { useSupabaseClient } from './useSupabaseClient'
 import { useState } from '#imports'
 
 export const useSupabaseUser = () => {
-  const supabase = useSupabaseClient()
-
-  const user = useState<User | null>('supabase_user', () => null)
-
-  // Asyncronous refresh session and ensure user is still logged in
-  supabase?.auth.getSession().then(({ data: { session } }) => {
```
Comment (larbish) [inline src/runtime/composables/useSupabaseUser.ts:11]: "useSupabaseUser() relies on useState(), which is updated on auth events from the supabase client" => Why not keeping this async call to also relies on the useSupabaseUser call ?

File: src/runtime/plugins/supabase.client.ts [hunk 2]
```diff
@@ -14,32 +14,34 @@ export default defineNuxtPlugin({
...
+      }
+      if (event === 'USER_UPDATED') {
+        if (session?.user) {
+          user.value = session.user
+        }
       }
     })
 
+    // attempt to retrieve an existing session from local storage
+    await supabaseClient.auth.getSession()
```
Comment (larbish) [inline src/runtime/plugins/supabase.client.ts:39]: This call fix the client rendered page issue since it ensures the session/user is set on client side refresh. It means we need to update the `confirm.vue` page in the playground and the documentation (also mention it in the release):

```
const user = useSupabaseUser()
if (user.value) {
  await navigateTo('/user')
}
```

**Review by larbish — CHANGES_REQUESTED** [review]
Sorry for the late review. I let my labtop at home during holidays 🌴 

The main idea seems good to me. However, I would like to discuss some points, what do you think about my comments, let me know.

**Review by larbish — APPROVED** [review]
